[package]
name = "siddhi_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
uuid = { version = "1", features = ["v4"] }
rand = "0.8"
crossbeam-channel = "0.5"
