version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: siddhi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --appendonly yes
      --appendfilename "siddhi-redis.aof"
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - siddhi-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: siddhi-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - siddhi-network

volumes:
  redis-data:
    driver: local

networks:
  siddhi-network:
    driver: bridge